name: tekartik_cmd_record
description: Record command line process stdout, stderr and stdin
version: 0.3.0
homepage: https://github.com/tekartik/cmd_record.dart

publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  process_run: ">=1.2.1+1"
  args: ">=2.6.0"
  path: ">=1.9.0"
  pub_semver: ">=2.1.4"
  tekartik_cmd_echo:
    git:
      url: https://github.com/tekartikprj/io_tools
      ref: dart3a
      path: packages/cmd_echo
dev_dependencies:
  test: ">=1.24.0"
  dev_test: ">=1.0.0+4"

dependency_overrides:
  tekartik_cmd_echo:
    path: ../cmd_echo
#  process_run:
#    git: https://github.com/tekartik/process_run.dart
#    version: ">=0.5.4"
#    path: ../process_run.dart
executables:
  cmd_record:
