name: tekartik_cmd_record
description: Record command line process stdout, stderr and stdin
version: 0.3.0
homepage: https://github.com/tekartik/cmd_record.dart

publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  process_run: ">=1.2.4"
  args: ">=2.7.0"
  path: ">=1.9.1"
  pub_semver: ">=2.2.0"
  tekartik_cmd_echo:
    git:
      url: https://github.com/tekartikprj/io_tools
      path: packages/cmd_echo
dev_dependencies:
  test: ">=1.26.3"
  dev_test: ">=1.0.1"

#  process_run:
#    git: https://github.com/tekartik/process_run.dart
#    version: ">=0.5.4"
#    path: ../process_run.dart
executables:
  cmd_record:
resolution: workspace
