# Dependabot configuration file.
# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
version: 2

enable-beta-ecosystems: true

updates:
  - package-ecosystem: "pub"
    directory: "packages/cmd_echo"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "packages/cmd_record"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "packages/cmd_tools"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
